name: Release Binaries

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*" # Push events to matching v*, i.e. v1.0, v20.15.10, v1.2.3-hotfix, etc.

permissions:
  contents: write # for goreleaser/goreleaser-action to create a GitHub release

jobs:
  binary:
    runs-on: ubuntu-latest
    env:
      working-directory: go/src/github.com/ignite/cli
    
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{ env.working-directory }}
          fetch-depth: 0

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          workdir: ${{ env.working-directory }}
          version: 1.13.0
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
